[project]
name = "droic"
version = "0.1b0"
description = "A dash app to monitor android metrics using adb and store the data locally in a database."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=3.0.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
]
